### ISSUE TITLE
How do I import these?

### ISSUE THREAD

**Issue by bahree** [dburkland/ios_shortcuts#1]
Hi, these look quite interesting - thank you for helping create this. The question I have is - how do I get started? All of these are binary files. Do I need to browse the repo on the phone or ipad?

And separately how did you export the shortcuts? Is there a tool / editor that one can use to view and modify?

Thanks.

**Comment by dburkland** [comment]
Hi bahree,

To import these shortcuts onto your iOS device you first need to make sure the Shortcuts app from Apple is installed. Once you have the app installed on your device browse to each .shortcut file on this [page](https://github.com/dburkland/ios_shortcuts/tree/master/tesla) and click "View Raw". This should result in the Shortcuts App opening and then it'll prompt you to save the shortcut. Rinse and repeat for each shortcut until you have them all imported to your device. From the app you can pick each shortcut apart and see what's going on under the hood or simply execute the shortcuts. For me on my iOS devices I use the Shortcuts widget for easy access as seen [here](https://www.dropbox.com/s/pacc0l56dd20fod/IMG_0163.PNG?dl=0). Let me know if you have any further questions!

Dan
