### ISSUE TITLE
Support for EU / Celsius 

### ISSUE THREAD

**Issue by himynamesned** [dburkland/ios_shortcuts#6]
As title. I believe this can be pulled from Tesla API

**Comment by himynamesned** [comment]
For example; heated driver’s seat on max defrost -currently defrosts the passenger seat on RHD. The API can check this value

**Comment by dburkland** [comment]
@himynamesned I took your request and added the following to my Tesla iOS shortcuts:

- Driver's seat detection logic
- Support for imperial and metric temperature units

For more information please refer to the README -> https://buff.ly/2Q6SEfM.

Happy Holidays!

Dan
